// techsConfig.js - 所有科技配置
const TECHS_CONFIG = {
    "伐木技术": { price: {科学: 5}, prereq: null, desc: "要致富，先撸树！", unlocks: ["伐木场"], researched: false },
    "采石技术": { price: {科学: 5}, prereq: ["伐木技术"], desc: "徒手挖石头", unlocks: ["采石场"], researched: false },
    "印刷术": { price: {科学: 10}, prereq: ["伐木技术"], desc: "印刷术是人类近代文明的先导，为知识的广泛传播、交流创造了条件。", unlocks: ["图书馆"], researched: false },
    "高效采石": { price: {科学: 400}, prereq: ["矿物学"], desc: "尝试优化开采石头的效率，解锁新的升级。", unlocksUpgrades: ["采石场优化"], researched: false },
    "基础储存技术": { price: {科学: 10}, prereq: ["采石技术"], desc: "解锁仓库，让你可以储存少量资源。", unlocks: ["仓库"], researched: false },
    "木制工具": { price: {科学: 20,木头: 150}, prereq: ["伐木技术"], desc: "伐木场/采石场速度+20%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.20}}, researched: false },
    "石制工具": { price: {科学: 30,石头: 150}, prereq: ["木制工具"], desc: "伐木场/采石场速度+20%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.20}}, researched: false },
    "铁制工具": { price: {科学: 200,铁: 50}, prereq: ["铁冶炼"], desc: "伐木场/采石场速度+30%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.30}}, unlocks: ["工具加工站"], researched: false },
    "钢制工具": { price: {科学: 500,钢: 50}, prereq: ["炼钢技术"], desc: "伐木场/采石场速度+30%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.30}}, researched: false },
    "碳纤维工具": { price: {科学: 1200,碳纤维: 150}, prereq: ["碳纤维材料"], desc: "伐木场/采石场速度+50%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.50}}, researched: false },
    "钛制工具": { price: {科学: 2500,钛: 150}, prereq: ["进阶月球采矿"], desc: "伐木场/采石场速度+50%",
        effect: {伐木场: {prodFactor: 0.20}, 采石场: {prodFactor: 0.50}}, researched: false },
    "杜威分类法": { price: {科学: 150}, prereq: ["印刷术"], desc: "图书馆科学上限+100%",
        effect: {图书馆: {capFactor: 1.00}}, researched: false },
    "煤矿生产": { price: {科学: 60}, prereq: ["石制工具"], desc: "解锁煤矿", unlocks: ["煤矿"], researched: false },
    "化学": { price: {科学: 120,石头: 200}, prereq: ["印刷术"], desc: "化学是一门在微观层面洞悉物质奥秘的自然科学", researched: false },
    "铜冶炼": { price: {科学: 150,煤: 10}, prereq: ["化学"], desc: "以黄铜矿等硫化铜精矿为原料，通过焙烧、熔炼、吹炼、精炼等工序提取金属铜", unlocks: ["铜冶炼厂"], researched: false },
    "铁冶炼": { price: {科学: 180,煤: 20}, prereq: ["煤矿生产"], desc: "在高温下，用还原剂将铁矿石还原得到生铁", unlocks: ["铁冶炼厂"], researched: false },
    "管理学": { price: {科学: 200}, prereq: ["铁冶炼"], desc: "管理学是研究管理规律、方法与模式，以提升组织效益的综合性交叉学科。", unlocks: ["行政机关"], unlocksPolicies: ["基础资源政策"], researched: false },
    "军事理论": { price: {科学: 150}, prereq: ["管理学"], desc: "解锁军营，可以生产军备并发动战争。", unlocks: ["军营"], researched: false },
    "军工技术":{ price: {科学: 800,钢: 200}, prereq: ["军事理论"], desc: "建设军工厂来提高战斗力", unlocks: ["军工厂"], researched: false },
    "冶炼管理": { price: {科学: 300,铁: 20}, prereq: ["管理学"], desc: "解锁冶炼方式政策", unlocksPolicies: ["冶炼方式"], researched: false },
    "初等数学": { price: {科学: 200}, prereq: ["印刷术"], desc: "初等数学涵盖算术、代数、几何、三角学及概率统计等基础内容", researched: false },
    "微积分": { price: {科学: 220}, prereq: ["初等数学"], desc: "微积分是研究函数变化率和累积变化的数学分支，主要包括微分学、积分学及其应用。", unlocks: ["大学"], researched: false },
    "高等代数": { price: {科学: 450}, prereq: ["微积分"], desc: "高等代数是代数学发展到高级阶段的总称，主要包括线性代数和多项式代数两大分支。大学科学上限+20%",
        effect: {大学: {capFactor: 0.20}}, researched: false },
    "牛顿力学": { price: {科学: 250}, prereq: ["初等数学"], desc: "研究低速宏观弱引力下的物体运动规律。", researched: false },
    "相对论":{ price: {科学: 500}, prereq: ["牛顿力学"], desc: "时空是一个整体，也许我们有办法穿越时间。", researched: false },
    "电磁感应": { price: {科学: 300}, prereq: ["牛顿力学"], desc: "解锁蒸汽机，准确来说是蒸汽发电机。", unlocks: ["蒸汽机"], researched: false },
    "热学": { price: {科学: 300}, prereq: ["牛顿力学"], desc: "研究如何更好利用热量", researched: false },
    "改良蒸汽机": { price: {科学: 320,煤: 30}, prereq: ["热学"], desc: "蒸汽机电力+20%",
        effect: {蒸汽机: {prodFactor: 0.2}}, researched: false },
    "进阶存储技术": { price: {科学: 350,铁: 30}, prereq: ["基础储存技术"], desc: "解锁集装箱", unlocks: ["集装箱"], researched: false },
    "压缩存储技术": { price: {科学: 500,建材: 20}, prereq: ["进阶存储技术"], desc: "解锁储存优化升级", unlocksUpgrades: ["储存优化"], researched: false },
    "初级建筑学": { price: {科学: 300,铁: 30}, prereq: ["基础储存技术"], desc: "解锁建材工厂", unlocks: ["建材工厂"], researched: false },
    "高级建筑学": { price: {科学: 400,建材: 60}, prereq: ["初级建筑学"], desc: "建材工厂建材产量+100%",
        effect: {建材工厂: {prodFactor: 1.00}}, researched: false },
    "林业工程": { price: {科学: 500}, prereq: ["初级建筑学"], desc: "林业工程，是指以森林资源的高效利用和可持续发展为原则，将各种工程技术应用于森林资源培育、开发利用及林产品加工的活动", unlocksUpgrades: ["伐木场优化"], researched: false },
    "矿物学": { price: {科学: 400,石头: 300}, prereq: ["化学"], desc: "解锁大型煤矿", unlocks: ["大型煤矿"], researched: false },
    "高效冶炼": { price: {科学: 450,铜: 200,铁: 200}, prereq: ["矿物学"], desc: "铜/铁冶炼厂产量+50%",
        effect: {铜冶炼厂: {prodFactor: 0.50}, 铁冶炼厂: {prodFactor: 0.50}}, researched: false },
    "金精炼": { price: {科学: 400,石头: 500}, prereq: ["矿物学"], desc: "解锁金矿", unlocks: ["金矿"], researched: false },
    "国际贸易学": { price: {科学: 600,金: 5}, prereq: ["金精炼"], desc: "解锁市场", unlocks: ["市场"], researched: false },
    "金融学": { price: {科学: 700,金: 20}, prereq: ["国际贸易学"], desc: "解锁经济观念政策", unlocksPolicies: ["经济观念"], researched: false },
    "炼钢技术": { price: {科学: 400,铁: 100}, prereq: ["化学"], desc: "炼钢技术是将生铁熔炼成钢，通过控制碳含量、去除有害元素并调整合金成分以获得所需性能的工艺", unlocks: ["炼钢厂"], researched: false },
    "电解铝": { price: {科学: 420}, prereq: ["矿物学"], desc: "电解铝是通过电解氧化铝获得金属铝的工业生产方法，是现代铝工业的核心工艺。", unlocks: ["电解铝厂"], researched: false },
    "拜耳法":{ price: {科学: 500}, prereq: ["电解铝"], desc: "拜耳法是一种工业上广泛使用的从铝土矿生产氧化铝的化工过程,电解铝厂的产出+50%",
        effect: {电解铝厂: {prodFactor: 0.50}}, researched: false },
    "金属加工": { price: {科学: 450}, prereq: ["电解铝"], desc: "解锁金属加工厂金属加工是以金属材料进行加工的生产活动，涵盖从大型工业零件到精密组件的制造工艺", unlocks: ["金属加工厂"], researched: false },
    "运筹学": { price: {科学: 600}, prereq: ["高等代数"], desc: "运筹学主要目的是在决策时为管理人员提供科学依据，是实现有效管理、正确决策和现代化管理的重要方法之一", unlocksUpgrades: ["工厂优化"], researched: false },
    "大宗存储技术": { price: {科学: 480}, prereq: ["金属加工"], desc: "解锁大型仓库", unlocks: ["大型仓库"], researched: false },
    "有机化学": { price: {科学: 500}, prereq: ["电解铝"], desc: "有机化学是研究有机化合物的组成、结构、性质、制备方法与应用的科学", unlocks: ["油田"], researched: false },
    "生物学":{ price: {科学: 1000}, prereq: ["有机化学"], desc: "研究生物的科学", researched: false },
    "基因编辑":{ price: {科学: 10000}, prereq: ["生物学"], desc: "人们开始尝试编辑自己的基因，科学家警告这可能造成严重后果", researched: false },
    "碳纤维亲和":{
        price: {科学: 15000}, prereq: ["基因编辑"], desc: "⚠️这是一种使人更加适应碳纤维的基因，但是副作用是人们变得更笨了，且目前没有任何手段消除该副作用。碳纤维厂产出+100%，大学科学上限-10%",
        effect: {碳纤维厂: {prodFactor: 1.0}, 大学: {capFactor: -0.1}}, researched: false
    },
    "保守基因":{
        price: {科学: 15000}, prereq: ["基因编辑"], desc: "⚠️这是一种使人更加保守和不愿探索的基因，且目前没有任何手段消除该副作用。月球基地产出-10%，蒸汽机和石油发电厂产出+20%",
        effect: {石油发电厂: {prodFactor: 0.2}, 蒸汽机: {prodFactor: 0.2}, 月球基地: {prodFactor: -0.2}}, researched: false
    },
    "材料化学": { price: {科学: 550}, prereq: ["有机化学"], desc: "材料化学是一门从化学角度研究和设计材料的学科，强调材料的组成、结构与性能之间的关系，并结合实验与应用开发新材料", unlocks: ["科学院"], researched: false },
    "石油加工": { price: {科学: 550}, prereq: ["有机化学"], desc: "石油加工是将原油通过物理分离和化学转化加工成燃料油及化工原料的工业体系，包括预处理、蒸馏、催化裂化、加氢处理、精制及化工延伸等多个环节", unlocks: ["塑料厂"], researched: false },
    "石油发电":{ price: {科学: 600,石油: 50}, prereq: ["石油加工"], desc: "石油发电主要通过燃烧原油或石油制品产生高温蒸汽或直接驱动内燃机，推动发电机发电", unlocks: ["石油发电厂"], researched: false },
    "太阳能": { price: {科学: 800}, prereq: ["石油加工"], desc: "太阳能是由太阳内部氢原子发生氢氦聚变释放出巨大核能而产生的，来自太阳的辐射能量", unlocks: ["太阳能板"], researched: false },
    "能源规划":{ price: {科学: 900}, prereq: ["太阳能"], desc: "更好地规划能源设施的建造", unlocksPolicies: ["能源政策"], researched: false },
    "储能技术": { price: {科学: 700}, prereq: ["金属加工"], desc: "储能是通过介质或设备将能量存储起来，并在需要时释放的技术体系，是电力系统高效运行的核心支撑", unlocks: ["电池"], researched: false },
    "原子结构模型": { price: {科学: 800}, prereq: ["储能技术"], desc: "通过α粒子散射实验建立原子核式模型", researched: false },
    "核物理": { price: {科学: 900}, prereq: ["原子结构模型"], desc: "核物理是研究原子核结构、性质及其相互作用规律的物理学分支，同时为核能、核技术及相关应用提供理论和技术基础", unlocks: ["铀矿"], researched: false },
    "核裂变": { price: {科学: 1000,铀: 20}, prereq: ["核物理"], desc: "尝试从原子核中提取能量", unlocks: ["裂变反应堆"], researched: false },
    "核裂变改进":{ price: {科学: 2000,铀: 500}, prereq: ["核燃料"], desc: "确保安全的前提下提高核裂变的速度", unlocksUpgrades: ["高速反应堆"], researched: false },
    "浓缩铀": { price: {科学: 1050,铀: 50}, prereq: ["核裂变"], desc: "铀矿产量+50%",
        effect: {铀矿: {prodFactor: 0.50}}, researched: false },
    "量子力学":{ price: {科学: 1200}, prereq: ["核裂变"], desc: "量子力学是现代物理学的基础，描述了微观世界的行为，涵盖了从原子到亚原子粒子的各种现象", unlocks: ["粒子加速器"], researched: false },
    "碳纤维材料": { price: {科学: 1100}, prereq: ["有机化学"], desc: "解锁碳纤维厂", unlocks: ["碳纤维厂"], researched: false },
    "天体物理": { price: {科学: 1300,铀: 30}, prereq: ["核裂变"], desc: "天体物理学是研究天体物理性质、化学组成及演化规律的科学，是天文学与物理学的交叉学科", researched: false },
    "核燃料": { price: {科学: 1600,铀: 50}, prereq: ["天体物理"], desc: "解锁核燃料工厂", unlocks: ["核燃料工厂"], researched: false },
    "火箭动力学": { price: {科学: 1800,核燃料: 10}, prereq: ["核燃料"], desc: "火箭技术", researched: false },
    "探索月球": { price: {科学: 2000,核燃料: 30}, prereq: ["火箭动力学"], desc: "解锁月球基地", unlocks: ["月球基地"], researched: false },
    "宜居化改造":{ price: {科学: 3000}, prereq: ["探索月球"], desc: "提高人们对太空环境的适应能力", unlocksUpgrades: ["宜居化改造"], researched: false },
    "太空剧院":{ price: {科学: 5000,暗能量: 1}, prereq: ["宜居化改造"], desc: "利用暗能量来表演精彩的魔术", unlocks: ["太空剧院"], researched: false },
    "基础月球采矿": { price: {科学: 2500,核燃料: 50}, prereq: ["探索月球"], desc: "解锁月球铁矿/铜矿", unlocks: ["月球铁矿","月球铜矿"], researched: false },
    "进阶月球采矿": { price: {科学: 3000,核燃料: 100}, prereq: ["基础月球采矿"], desc: "解锁月球钛矿", unlocks: ["月球钛矿"], researched: false },
    "研究月球": { price: {科学: 3500,核燃料: 150}, prereq: ["探索月球"], desc: "解锁月球研究所", unlocks: ["月球研究所"], researched: false },
    "月球工厂":{ price: {科学: 4000,铜: 2000,铁: 2000}, prereq: ["研究月球"], desc: "解锁提升工厂效率的月球工厂", unlocks: ["月球工厂"], researched: false },
    "轨道电梯": {
        price: {科学: 8000, 碳纤维: 1000, 钛: 800},
        prereq: ["月球工厂"],
        desc: "解锁轨道电梯，提升月球生产效率",
        unlocks: ["轨道电梯"],
        researched: false
    },
    "星际航行":{
        price: {科学: 15000,核燃料: 10000}, prereq: ["月球工厂"], desc: "探索更加遥远的宇宙空间", researched: false
    },
    "星际交易":{
        price: {科学: 16000,金: 10000}, prereq: ["星际航行"], unlocks: ["星际交易站"], desc: "建立星际交易站，大幅提高交易效率", researched: false
    },
    "探索气态行星":{ price: {科学: 18000,核燃料: 20000}, prereq: ["星际航行"], desc: "探索一颗巨大的气态行星，也许能找到新的燃料来源", unlocks: ["气态行星基地"], researched: false },
    "氚提取":{ price: {科学: 20000}, prereq: ["探索气态行星"], desc: "在气态行星上提取氚", unlocks: ["氚提取站"], researched: false },
    "氚处理":{ price: {科学: 22000}, prereq: ["氚提取"], desc: "建立氚工厂生成核燃料", unlocks: ["氚燃料厂"], researched: false },
    "可控核聚变":{ price: {科学: 25000}, prereq: ["氚处理"], desc: "建立聚变反应堆来生产电力", unlocks: ["聚变反应堆"], researched: false },
    "聚变规模化":{ price: {科学: 40000}, prereq: ["可控核聚变"], desc: "扩大聚变反应堆的规模", unlocksUpgrades: ["聚变规模化"], researched: false },
    "戴森球计划":{ price: {科学: 100000}, prereq: ["月球工厂"], desc: "使用一个巨大的球体来提取恒星的能量，需要大量资源", unlocks: ["戴森球"], researched: false },
    "暗物质探测":{ price: {科学: 6000}, prereq: ["研究月球"], desc: "在太空中探测暗物质的踪迹，它真的存在吗?", researched: false },
    "暗物质利用":{ price: {科学: 10000}, prereq: ["暗物质探测"], desc: "我们也许可以从暗物质中提取能量，但是代价是什么?", unlocks: ["暗物质研究所"], researched: false },
    "真空衰变":{ price: {科学: 20000}, prereq: ["暗物质利用"], desc: "科学家警告利用暗物质能量可能造成灾难性的结果，我们应该放弃吗?", researched: false },
    "曼哈顿计划": { price: {科学: 1500,铀: 100}, prereq: ["核裂变"], desc: "解锁核弹", researched: false },
    "探索遗迹": { price: {科学: 500,遗物: 1}, prereq: ["矿物学"], desc: "研究奇怪的遗物，解锁博物馆", unlocks: ["博物馆"], researched: false },
    "奇怪的石头":{ price: {科学: 500,石头: 1000}, prereq: ["采石技术"], desc: "人们在采集石头时发现一块奇怪的大石头，它表面十分光滑，还刻有神秘符号,没有人知道这是什么意思", researched: false },
    "既视感":{ price: {科学: 5000}, prereq: ["奇怪的石头"], desc: "考古人员在研究这个奇怪的石头时感觉似曾相识。石头吸引来很多人的兴趣，他们都有类似的感觉:他们曾经见过这块石头", researched: false },
    "石头的低语":{ price: {科学: 40000,暗能量: 1}, prereq: ["既视感"], desc: "科学家发现这个奇怪的石头似乎能够影响暗物质的分布。暗物质研究所产量增加50%",
        effect: {暗物质研究所: {prodFactor: 0.50}}, researched: false },
    "尝试破解石头":{ price: {科学: 400000}, prereq: ["石头的低语"], desc: "使用超级量子计算机破译石头上的文字", researched: false }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { TECHS_CONFIG };
}