const RESOURCES_CONFIG = {
    "电力":       { baseCap: 50 },
    "木头":       { baseCap: 100, value: 1, },
    "石头":       { baseCap: 100, value: 1, },
    "科学":       { baseCap: 100 },
    "政策点":     { baseCap: 100 },
    "煤":         { baseCap: 100, value: 1.5,  },
    "铜":         { baseCap: 50,  value: 3,  },
    "铁":         { baseCap: 50,  value: 3,   },
    "铝":         { baseCap: 50,  value: 4,   },
    "金":         { baseCap: 50 },
    "钢":         { baseCap: 50,  value: 6,    },
    "钛":         { baseCap: 50,  value: 8,    },
    "建材":       { baseCap: 50,  value: 5,    },
    "石油":       { baseCap: 50,  value: 4,    },
    "塑料":       { baseCap: 50,  value: 6,    },
    "金属板":     { baseCap: 50,  value: 7,   },
    "碳纤维":     { baseCap: 50,  value: 12,   },
    "铀":         { baseCap: 50,  value: 10,   },
    "氚":         { baseCap: 50 },
    "核燃料":     { baseCap: 50,  value: 20,   },
    "军备":       { baseCap: 100 },
    "遗物":       { baseCap: 1000000 },
    "暗能量":     { baseCap: 1000000 },
    "时间晶体":   { baseCap: 36000 }
};