const RESOURCES_CONFIG = {
    "电力":       { baseCap: 50 },
    "木头":       { baseCap: 100, value: 1,   heat: 1 },
    "石头":       { baseCap: 100, value: 2,   heat: 1 },
    "科学":       { baseCap: 100 },
    "政策点":     { baseCap: 100 },
    "煤":         { baseCap: 100, value: 1.5, heat: 1 },
    "铜":         { baseCap: 50,  value: 3,   heat: 1 },
    "铁":         { baseCap: 50,  value: 3,   heat: 1 },
    "铝":         { baseCap: 50,  value: 4,   heat: 1 },
    "金":         { baseCap: 50 },
    "钢":         { baseCap: 50,  value: 6,   heat: 1 },
    "钛":         { baseCap: 50,  value: 8,   heat: 1 },
    "建材":       { baseCap: 50,  value: 5,   heat: 1 },
    "石油":       { baseCap: 50,  value: 4,   heat: 1 },
    "塑料":       { baseCap: 50,  value: 6,   heat: 1 },
    "金属板":     { baseCap: 50,  value: 7,   heat: 1 },
    "碳纤维":     { baseCap: 50,  value: 12,  heat: 1 },
    "铀":         { baseCap: 50,  value: 15,  heat: 1 },
    "氚":         { baseCap: 50 },
    "核燃料":     { baseCap: 50,  value: 20,  heat: 1 },
    "太空宜居度": { baseCap: 50 },
    "军备":       { baseCap: 100 },
    "遗物":       { baseCap: 1000000 },
    "暗能量":     { baseCap: 1000000 },
    "时间晶体":   { baseCap: 1000000 }
};